import image from '../../assets/profilePic.png'

let info = {
    lead: [
        {
            name: "Shreya Dhurde",
            position: "Lead",
            profilePic: image,
            shadow: "#F74037",
            insta: "",
            github: "",
            linkedIn: "",
        },
        {
            name: "Dipali Patil",
            position: "Faculty Coordinator",
            profilePic: image,
            shadow: "#F74037",
            insta: "",
            github: "",
            linkedIn: "",
        }
    ],
    teams: {
        technical: [
            {
                name: "Om Gawande",
                position: "Web Specialist",
                profilePic: image,
                shadow: "#4285F4",
                insta: "",
                github: "",
                linkedIn: "",
            },
            {
                name: "Palash Rambhia",
                position: "Android Specialist",
                profilePic: image,
                shadow: "#14B25F",
                insta: "",
                github: "",
                linkedIn: "",
            },
            {
                name: "Simran Khaparde",
                position: "CyberSecurity Specialist",
                profilePic: image,
                shadow: "#FBBC04",
                insta: "",
                github: "",
                linkedIn: "",
            },
            {
                name: "Onkar Waghmode",
                position: "Tech Coordinator",
                profilePic: image,
                shadow: "#14B25F",
                insta: "",
                github: "",
                linkedIn: "",
            },
            {
                name: "Ayush Ahire",
                position: "Tech Coordinator",
                profilePic: image,
                shadow: "#4285F4",
                insta: "",
                github: "",
                linkedIn: "",
            },
            {
                name: "Shweta Mandal",
                position: "Tech Coordinator",
                profilePic: image,
                shadow: "#F74037",
                insta: "",
                github: "",
                linkedIn: "",
            }
            
        ],
        design: [
            {
                name: "Saurabh Barde",
                position: "Design Lead",
                profilePic: image,
                shadow: "#F74037",
                insta: "",
                github: "",
                linkedIn: "",
            },
            {
                name: "Sakshi Thombre",
                position: "Design Lead",
                profilePic: image,
                shadow: "#F74037",
                insta: "",
                github: "",
                linkedIn: "",
            },
            {
                name: "Kartik Bankar",
                position: "Design Coordinator",
                profilePic: image,
                shadow: "#F74037",
                insta: "",
                github: "",
                linkedIn: "",
            },
            {
                name: "Nikita Thakur",
                position: "Design Coordinator",
                profilePic: image,
                shadow: "#F74037",
                insta: "",
                github: "",
                linkedIn: "",
            },
            {
                name: "Raunak Mesharam",
                position: "Design Coordinator",
                profilePic: image,
                shadow: "#F74037",
                insta: "",
                github: "",
                linkedIn: "",
            },
        ],
        management: [
            {
                name: "Abhishek Suryawanshi",
                position: "Management Lead",
                profilePic: image,
                shadow: "#F74037",
                insta: "",
                github: "",
                linkedIn: "",
            },
            {
                name: "Ashutosh Shimpi",
                position: "Management Lead",
                profilePic: image,
                shadow: "#F74037",
                insta: "",
                github: "",
                linkedIn: "",
            },
            {
                name: "Soham Wadje",
                position: "Management Coordinator",
                profilePic: image,
                shadow: "#F74037",
                insta: "",
                github: "",
                linkedIn: "",
            },
            {
                name: "Prathamesh Nigade",
                position: "Management Coordinator",
                profilePic: image,
                shadow: "#F74037",
                insta: "",
                github: "",
                linkedIn: "",
            },
        ],
        pr: [
            {
                name: "Vaishnavi Mokadam",
                position: "PR Lead",
                profilePic: image,
                shadow: "#F74037",
                insta: "",
                github: "",
                linkedIn: "",
            },
            {
                name: "Vaishnavi Barge",
                position: "PR Lead",
                profilePic: image,
                shadow: "#F74037",
                insta: "",
                github: "",
                linkedIn: "",
            },
            {
                name: "Yash Dhoot",
                position: "PR Coordinator",
                profilePic: image,
                shadow: "#F74037",
                insta: "",
                github: "",
                linkedIn: "",
            },
            {
                name: "Neelam Pawar",
                position: "PR Coordinator",
                profilePic: image,
                shadow: "#F74037",
                insta: "",
                github: "",
                linkedIn: "",
            },
        ],
        
    }
};

export default info