let info = [
    {
        projectName: "Athena",
        domain: "Android Development",
        author: "Palash Rambhia",
        summary: "A short story writing app called Athena gives users a head start by generating a story between 100 and 200 words long based on their preferences.",
        tags: ["#android", "#development", "#palash", "#gdsc"],
        linkedin: "https://www.linkedin.com/in/palashrambhia/",
        github: "https://github.com/Palash2911/Athena",
        more: "https://github.com/Palash2911/Athena",
    },
    {
        projectName: "Athena",
        domain: "Android Development",
        author: "Palash Rambhia",
        summary: "A short story writing app called Athena gives users a head start by generating a story between 100 and 200 words long based on their preferences.",
        tags: ["#android", "#development", "#palash", "#gdsc"],
        linkedin: "https://www.linkedin.com/in/palashrambhia/",
        github: "https://github.com/Palash2911/Athena",
        more: "https://github.com/Palash2911/Athena",
    },
    {
        projectName: "Athena",
        domain: "Android Development",
        author: "Palash Rambhia",
        summary: "A short story writing app called Athena gives users a head start by generating a story between 100 and 200 words long based on their preferences.",
        tags: ["#android", "#development", "#palash", "#gdsc"],
        linkedin: "https://www.linkedin.com/in/palashrambhia/",
        github: "https://github.com/Palash2911/Athena",
        more: "https://github.com/Palash2911/Athena",
    },
    {
        projectName: "Athena",
        domain: "Android Development",
        author: "Palash Rambhia",
        summary: "A short story writing app called Athena gives users a head start by generating a story between 100 and 200 words long based on their preferences.",
        tags: ["#android", "#development", "#palash", "#gdsc"],
        linkedin: "https://www.linkedin.com/in/palashrambhia/",
        github: "https://github.com/Palash2911/Athena",
        more: "https://github.com/Palash2911/Athena",
    },
    {
        projectName: "Athena",
        domain: "Android Development",
        author: "Palash Rambhia",
        summary: "A short story writing app called Athena gives users a head start by generating a story between 100 and 200 words long based on their preferences.",
        tags: ["#android", "#development", "#palash", "#gdsc"],
        linkedin: "https://www.linkedin.com/in/palashrambhia/",
        github: "https://github.com/Palash2911/Athena",
        more: "https://github.com/Palash2911/Athena",
    },
    {
        projectName: "Athena",
        domain: "Android Development",
        author: "Palash Rambhia",
        summary: "A short story writing app called Athena gives users a head start by generating a story between 100 and 200 words long based on their preferences.",
        tags: ["#android", "#development", "#palash", "#gdsc"],
        linkedin: "https://www.linkedin.com/in/palashrambhia/",
        github: "https://github.com/Palash2911/Athena",
        more: "https://github.com/Palash2911/Athena",
    },
    {
        projectName: "Athena",
        domain: "Android Development",
        author: "Palash Rambhia",
        summary: "A short story writing app called Athena gives users a head start by generating a story between 100 and 200 words long based on their preferences.",
        tags: ["#android", "#development", "#palash", "#gdsc"],
        linkedin: "https://www.linkedin.com/in/palashrambhia/",
        github: "https://github.com/Palash2911/Athena",
        more: "https://github.com/Palash2911/Athena",
    },
]

export default info;