import img1 from "../../assets/tagImg.png"

let info = [
    {
        projectName: "Athena",
        authors: ["Palash Rambhia"],
        tagImg: [img1],
        tags: ["Web Development, ", "Open Source"],
        languages: ["HTML, ", "Css, ", "JS", "ReactJS"],
        link: "",
        github: "https://github.com/Palash2911/Athena",
        color: "#EA4335"
    },
    {
        projectName: "Animating Buttons",
        authors: ["Om Gawande", "Palash Rambhia",],
        tagImg: [img1, img1, img1],
        tags: ["Web Development, ", "Open Source"],
        languages: ["HTML, ", "Css, ", "JS", "ReactJs"],
        link: "",
        github: "https://github.com/Spyware007/Animating-Buttons",
        color: "#0F9D58",
    },
    {
        projectName: "Tour India",
        authors: ["Om Gawande"],
        tagImg: [img1],
        tags: ["Web Development, ", "Open Source"],
        languages: ["HTML, ", "Css, ", "JS "],
        link: "",
        github: "https://github.com/Spyware007/TourIndia",
        color: "#0F9D58",
    },
    {
        projectName: "UN - Toxic",
        authors: ["Palash Rambhia"],
        tagImg: [img1],
        tags: ["Flutter Project"],
        languages: ["Dart", "Swift"],
        link: "",
        github: "https://github.com/Palash2911/UN-Toxic",
        color: "#4285F4",
    },
    {
        projectName: "SAHARA",
        authors: ["Shweta Mandal"],
        tagImg: [img1],
        tags: ["Web Development, ", "Open Source"],
        languages: ["HTML, ", "Css, ", "JS ", "ReactJS", "FireBase"],
        link: "",
        github: "https://github.com/Shweta2003/SAHARA",
        color: "#EA4335",
    },
    {
        projectName: "Helper",
        authors: ["Shweta Mandal"],
        tagImg: [img1],
        tags: ["Android Development, ", "Open Source"],
        languages: ["Android Studio", "Java", "FireBase"],
        link: "",
        github: "https://github.com/Shweta2003/Helper",
        color: "#0F9D58",
    },
    {
        projectName: "Rempo",
        authors: ["Om Gawande", "Palash Rambhia", "Saurabh Barde"],
        tagImg: [img1, img1, img1],
        tags: ["Flutter Project"],
        languages: ["Kotlin", "JavaScript", "CSS"],
        link: "",
        github: "https://github.com/Palash2911/Rempo",
        color: "#4285F4",
    },
]

export default info;